{{- if .Values.local }}
{{- else }}
{{- if .Values.runIntegrationTests }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.service.name }}-integration-tests
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.service.name }}-integration-tests
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.name }}-integration-tests
{{- end }}
{{- end }}
