{{- if .Values.local }}
{{- else }}
{{- if .Values.runIntegrationTests }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.service.name }}-integration-tests
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  - revisions
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}