# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# Add annotations to the pods
podAnnotations: {}
# Add labels to the pods
podsLabels: {}
# Add labels to the deployment
deploymentLabels: {}
image:
  repository: ghcr.io/cloudnativeentrepreneur/example-todo-model-service
  tag: v0.13.2
  pullPolicy: IfNotPresent
# define environment variables here as a map of key: value
env:
runIntegrationTests: true
# enable this flag to use knative serve to deploy the app
knativeDeploy: true
knative:
  minScale: 1
  maxScale: 1
  concurrencyTarget: 100
local: false
localKnativeSubscriber: http://host.docker.internal:5002
localKnativeDlqSubscriber: http://host.docker.internal:3999
service:
  name: example-todo-model-service
  type: ClusterIP
  internalPort: 5002
  externalPort: 80
  annotations: {}
  labels: {}
resources:
  limits:
    cpu: '1'
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /health
livenessProbe:
  initialDelaySeconds: 2
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 1
  successThreshold: 1
  timeoutSeconds: 1
sourced:
  psql:
    name: example-sourced-db-postgresql
    hostname: example-sourced-db-postgresql
imagePullSecrets: ghcr
