apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/docker-helm/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-container-build
          resources:
            requests:
              cpu: 1500m
              memory: 1500Mi
          env:
          - name: KANIKO_FLAGS
            value: --snapshotMode=redo
        - name: build-container-integration-tests
          image: gcr.io/kaniko-project/executor:v1.6.0-debug
          resources:
            requests:
              cpu: 1500m
              memory: 1500Mi
          env:
          - name: KANIKO_FLAGS
            value: --snapshotMode=redo
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=jest.integration.Dockerfile --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME-integration-tests:$VERSION
        - image: ghcr.io/jenkins-x-plugins/jx-preview:0.0.192
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx preview create
        - image: ghcr.io/jenkins-x/jx-boot:3.2.206
          name: verify-integration-tests
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx verify job --name `echo $APP_NAME-integration-tests-$VERSION | tr '[:upper:]' '[:lower:]'` -n $PREVIEW_NAMESPACE
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
