apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.repository.name }}-{{ .Values.pr }}-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/{{ .Values.repository.name }}.git
    targetRevision: {{ .Values.headRef }}
    helm:
      version: v3
      values: |
        image:
          tag: {{ .Values.tag }}
        env:
          EXAMPLE_HASURA_PROJECTIONS_URL: http://example-hasura-projections-service.example-prod-env.svc.cluster.local
          TODO_EVENTS_BROKER_URL: "http://broker-ingress.knative-eventing.svc.cluster.local/example-prod-env/todo-events"
  destination:
    namespace: {{ .Values.repository.name }}-{{ .Values.pr }}-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
