apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.repository.name }}-{{ .Values.pr }}-preview-sourced-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: charts/sourced-db
    repoURL: https://github.com/cloudnativeentrepreneur/sourced-db.git
    targetRevision: HEAD
    helm:
      version: v3
  destination:
    namespace: {{ .Values.repository.name }}-{{ .Values.pr }}-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true